### ISSUE TITLE
error al hacer build al flexget-arm

### ISSUE THREAD

**Issue by sastiam** [pablokbs/plex-rpi#26]
![image](https://user-images.githubusercontent.com/54696162/112762931-f664d800-8fc7-11eb-877a-743bc052a4b9.png)

Me menciona que existe una sintaxis invalida, este es mi Dockerfile
```
FROM armhf/alpine
MAINTAINER bren

RUN apk add --update \
  tzdata \
  python \
  py-pip \
  ca-certificates \
  && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11 \
  && rm -rf /var/cache/apk/*

RUN apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/main tinyxml2 && \
    apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community mediainfo && \
    apk add --update ffmpeg && \
    rm -rf /var/cache/apk/*

# Copy local files
COPY files/ /

# add default volumes
VOLUME /config /data
WORKDIR /config

# expose port for flexget webui
EXPOSE 3539 3539/tcp

# run init.sh to set uid, gid, permissions and to launch flexget
RUN chmod +x /scripts/init.sh
CMD ["/scripts/init.sh"]
```

De antemano, agradezco al que me pueda dar una mano con esto :)

**Comment by tpargmdiaz** [comment]
Tengo el mismo problema. A alguien más le pasa?

**Comment by MEvaVG12** [comment]
Hola! a mi me esta pasando. ¿Alguien sabe la solución?

**Comment by Fhorazombie** [comment]
![image](https://user-images.githubusercontent.com/16637078/133478781-82d5fec6-1ae8-4543-af75-ec8e7fb37d53.png)

Tengo el mismo error:
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Xcn2eH/guessit/setup.py", line 77, in <module>
        setup(**args)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Xcn2eH/guessit/
ERROR: Service 'flexget' failed to build: The command '/bin/sh -c apk add --update   tzdata   python   py-pip   ca-certificates   && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11   && rm -rf /var/cache/apk/*' returned a non-zero code: 1
