### ISSUE TITLE
Couldn't find index page for 'pytest-runner' (maybe misspelled?)

### ISSUE THREAD

**Issue by Fhorazombie** [pablokbs/plex-rpi#27]
![image](https://user-images.githubusercontent.com/16637078/133479690-bccc5121-f08a-48dd-9370-f9b1cf767851.png)

Me sale este error al hacer docker-compose up
Complete output from command python setup.py egg_info:
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-Xcn2eH/guessit/setup.py", line 77, in
setup(**args)
File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
_setup_distribution = dist = klass(attrs)
File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 315, in init
self.fetch_build_eggs(attrs['setup_requires'])
File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
replace_conflicting=True,
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 850, in resolve
dist = best[req.key] = env.best_match(req, ws, installer)
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 1122, in best_match
return self.obtain(req, installer)
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 1134, in obtain
return installer(requirement)
File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
return cmd.easy_install(req)
File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Xcn2eH/guessit/
ERROR: Service 'flexget' failed to build: The command '/bin/sh -c apk add --update tzdata python py-pip ca-certificates && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11 && rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by nicoib** [comment]
To solve this error only add de pytest-runner dependency in the command

```
RUN apk add --update \
  tzdata \
  python \
  py-pip \
  ca-certificates \
  **&& pip install pytest-runner \**
  && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.2 transmissionrpc==0.11 \
  && rm -rf /var/cache/apk/*
```
